<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Banner;
use App\Models\User;
use App\Models\UserProfile;

class ComprehensiveBannerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get admin user (created_by user id = 1)
        $adminProfile = UserProfile::find(1);

        if (!$adminProfile) {
            $this->command->warn('User profile with ID 1 not found. Please ensure users are seeded first.');
            return;
        }

        // Get customer user (purchaser_id user id = 13)
        $customer = User::find(13);

        if (!$customer) {
            $this->command->info('Customer user with ID 13 not found. Using admin as purchaser.');
            $customer = User::find(1);
        }

        // Local banner images - cycling through these
        $localImages = [
            'http://localhost/storage/images/banners/noaa-AdZUiGNo9Fo-unsplash.jpg',
            'http://localhost/storage/images/banners/noaa-AQx2VH2731k-unsplash.jpg',
            'http://localhost/storage/images/banners/noaa-WjK2_zZ8bRM-unsplash.jpg',
        ];

        $banners = [
            // ID 1 - Header Banner
            [
                'title' => 'Special Marine Equipment Sale - Up to 50% Off!',
                'description' => 'Limited time offer on premium marine equipment and accessories',
                'position' => 'hero',
                'banner_size' => 'large',
                'dimensions' => null,
                'mobile_dimensions' => null,
                'display_context' => 'homepage',
                'sort_order' => 0,
                'show_on_mobile' => true,
                'show_on_desktop' => true,
                'target_category_id' => null,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => null,
                'text_color' => null,
                'button_text' => null,
                'button_color' => null,
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[0],
                'link_url' => '/search-results?category=marine-equipment&sale=true',
                'priority' => 100,
                'status' => 'active',
                'start_date' => now()->subDays(20),
                'end_date' => now()->addDays(10),
                'click_count' => 0,
                'impression_count' => 308,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => $customer?->id,
                'purchase_price' => 50000.00,
                'purchase_status' => 'paid',
                'purchased_at' => now()->subDays(20),
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'header',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 2 - Hero Banner
            [
                'title' => 'Discover Premium Marine Equipment',
                'description' => 'Connect with verified sellers across Africa for boats, engines, and marine gear',
                'position' => 'middle',
                'banner_size' => 'large',
                'dimensions' => null,
                'mobile_dimensions' => null,
                'display_context' => 'homepage',
                'sort_order' => 0,
                'show_on_mobile' => true,
                'show_on_desktop' => true,
                'target_category_id' => null,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => null,
                'text_color' => null,
                'button_text' => null,
                'button_color' => null,
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[1],
                'link_url' => '/search-results',
                'priority' => 90,
                'status' => 'active',
                'start_date' => now()->subDays(20),
                'end_date' => now()->addDays(10),
                'click_count' => 0,
                'impression_count' => 239,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => $customer?->id,
                'purchase_price' => 80000.00,
                'purchase_status' => 'paid',
                'purchased_at' => now()->subDays(20),
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'hero',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 5 - Premium Marine Equipment Sale
            [
                'title' => 'Premium Marine Equipment Sale',
                'description' => 'Up to 30% off on premium boats, engines, and marine equipment. Limited time offer!',
                'position' => 'hero',
                'banner_size' => 'full_width',
                'dimensions' => json_encode(['width' => 1920, 'height' => 400]),
                'mobile_dimensions' => json_encode(['width' => 375, 'height' => 200]),
                'display_context' => 'homepage',
                'sort_order' => 1,
                'show_on_mobile' => true,
                'show_on_desktop' => true,
                'target_category_id' => null,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => '#0066cc',
                'text_color' => '#ffffff',
                'button_text' => 'Shop Sale',
                'button_color' => '#ff6600',
                'overlay_settings' => json_encode(['color' => '#000000', 'enabled' => true, 'opacity' => 0.3]),
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[2],
                'link_url' => '/equipment?sale=true',
                'priority' => 10,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => now()->addDays(16),
                'click_count' => 0,
                'impression_count' => 447,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => null,
                'purchase_price' => null,
                'purchase_status' => 'paid',
                'purchased_at' => null,
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'promotional',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 6 - New Boat Collection 2024
            [
                'title' => 'New Boat Collection 2024',
                'description' => 'Discover our latest collection of premium boats and yachts.',
                'position' => 'hero',
                'banner_size' => 'full_width',
                'dimensions' => json_encode(['width' => 1920, 'height' => 400]),
                'mobile_dimensions' => json_encode(['width' => 375, 'height' => 200]),
                'display_context' => 'homepage',
                'sort_order' => 2,
                'show_on_mobile' => true,
                'show_on_desktop' => true,
                'target_category_id' => 1,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => '#004080',
                'text_color' => '#ffffff',
                'button_text' => 'View Collection',
                'button_color' => '#ffffff',
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[0],
                'link_url' => '/equipment?category=boats&year=2024',
                'priority' => 9,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => now()->addDays(46),
                'click_count' => 0,
                'impression_count' => 447,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => null,
                'purchase_price' => null,
                'purchase_status' => 'paid',
                'purchased_at' => null,
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'featured',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 7 - Boats & Yachts
            [
                'title' => 'Boats & Yachts',
                'description' => 'Explore our premium boat collection',
                'position' => 'category_row',
                'banner_size' => 'small',
                'dimensions' => json_encode(['width' => 300, 'height' => 200]),
                'mobile_dimensions' => json_encode(['width' => 150, 'height' => 120]),
                'display_context' => 'homepage',
                'sort_order' => 1,
                'show_on_mobile' => true,
                'show_on_desktop' => true,
                'target_category_id' => 1,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => null,
                'text_color' => null,
                'button_text' => null,
                'button_color' => null,
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[1],
                'link_url' => '/equipment?category=boats',
                'priority' => 8,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => null,
                'click_count' => 0,
                'impression_count' => 247,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => null,
                'purchase_price' => null,
                'purchase_status' => 'paid',
                'purchased_at' => null,
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'category',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 8 - Marine Engines
            [
                'title' => 'Marine Engines',
                'description' => 'High-performance marine engines',
                'position' => 'category_row',
                'banner_size' => 'small',
                'dimensions' => json_encode(['width' => 300, 'height' => 200]),
                'mobile_dimensions' => json_encode(['width' => 150, 'height' => 120]),
                'display_context' => 'homepage',
                'sort_order' => 2,
                'show_on_mobile' => true,
                'show_on_desktop' => true,
                'target_category_id' => 6,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => null,
                'text_color' => null,
                'button_text' => null,
                'button_color' => null,
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[2],
                'link_url' => '/equipment?category=marine-engines',
                'priority' => 8,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => null,
                'click_count' => 0,
                'impression_count' => 249,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => null,
                'purchase_price' => null,
                'purchase_status' => 'paid',
                'purchased_at' => null,
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'category',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 9 - Safety Equipment
            [
                'title' => 'Safety Equipment',
                'description' => 'Essential marine safety gear',
                'position' => 'category_row',
                'banner_size' => 'small',
                'dimensions' => json_encode(['width' => 300, 'height' => 200]),
                'mobile_dimensions' => json_encode(['width' => 150, 'height' => 120]),
                'display_context' => 'homepage',
                'sort_order' => 3,
                'show_on_mobile' => true,
                'show_on_desktop' => true,
                'target_category_id' => 4,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => null,
                'text_color' => null,
                'button_text' => null,
                'button_color' => null,
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[0],
                'link_url' => '/equipment?category=safety-equipment',
                'priority' => 8,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => null,
                'click_count' => 0,
                'impression_count' => 251,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => null,
                'purchase_price' => null,
                'purchase_status' => 'paid',
                'purchased_at' => null,
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'category',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 10 - Flash Sale - Marine Electronics
            [
                'title' => 'Flash Sale - Marine Electronics',
                'description' => '48-hour flash sale on navigation and communication equipment',
                'position' => 'product_promotion',
                'banner_size' => 'medium',
                'dimensions' => json_encode(['width' => 600, 'height' => 300]),
                'mobile_dimensions' => json_encode(['width' => 375, 'height' => 200]),
                'display_context' => 'homepage',
                'sort_order' => 1,
                'show_on_mobile' => true,
                'show_on_desktop' => true,
                'target_category_id' => null,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => '#ff3300',
                'text_color' => '#ffffff',
                'button_text' => 'Shop Now',
                'button_color' => '#ffffff',
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => 10000,
                'max_clicks' => 500,
                'media_type' => 'image',
                'media_url' => $localImages[1],
                'link_url' => '/equipment?category=electronics&sale=true',
                'priority' => 7,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => now()->addDays(-12),
                'click_count' => 0,
                'impression_count' => 170,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => null,
                'purchase_price' => null,
                'purchase_status' => 'paid',
                'purchased_at' => null,
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'promotional',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 11 - Marine Insurance
            [
                'title' => 'Marine Insurance',
                'description' => 'Protect your investment with comprehensive marine insurance',
                'position' => 'sidebar',
                'banner_size' => 'small',
                'dimensions' => json_encode(['width' => 300, 'height' => 250]),
                'mobile_dimensions' => null,
                'display_context' => 'homepage',
                'sort_order' => 1,
                'show_on_mobile' => false,
                'show_on_desktop' => true,
                'target_category_id' => null,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => null,
                'text_color' => null,
                'button_text' => 'Get Quote',
                'button_color' => '#006600',
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[2],
                'link_url' => '/services/insurance',
                'priority' => 5,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => null,
                'click_count' => 0,
                'impression_count' => 244,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => null,
                'purchase_price' => null,
                'purchase_status' => 'paid',
                'purchased_at' => null,
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'service',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],

            // ID 12 - Equipment Financing
            [
                'title' => 'Equipment Financing',
                'description' => 'Flexible financing options for marine equipment purchases',
                'position' => 'sidebar',
                'banner_size' => 'small',
                'dimensions' => json_encode(['width' => 300, 'height' => 250]),
                'mobile_dimensions' => null,
                'display_context' => 'homepage',
                'sort_order' => 2,
                'show_on_mobile' => false,
                'show_on_desktop' => true,
                'target_category_id' => null,
                'target_locations' => null,
                'user_target' => 'all',
                'background_color' => null,
                'text_color' => null,
                'button_text' => 'Learn More',
                'button_color' => '#660066',
                'overlay_settings' => null,
                'conversion_rate' => 0.00,
                'max_impressions' => null,
                'max_clicks' => null,
                'media_type' => 'image',
                'media_url' => $localImages[0],
                'link_url' => '/services/financing',
                'priority' => 5,
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => null,
                'click_count' => 0,
                'impression_count' => 241,
                'revenue_earned' => 0.00,
                'created_by' => $adminProfile->id,
                'purchaser_id' => null,
                'purchase_price' => null,
                'purchase_status' => 'paid',
                'purchased_at' => null,
                'pricing_details' => null,
                'payment_reference' => null,
                'banner_type' => 'service',
                'duration_days' => 30,
                'auto_approve' => false,
                'admin_notes' => null,
            ],
        ];

        // Truncate existing banners
        Banner::truncate();

        // Insert banners
        foreach ($banners as $bannerData) {
            Banner::create($bannerData);
        }

        $this->command->info('✅ Comprehensive banners seeded successfully with local images!');
        $this->command->info('📊 Total banners created: ' . count($banners));
    }
}
